name: Test Installation Script
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ubuntu-version: ['20.04', '22.04']

    steps:
      - uses: actions/checkout@v4

      - name: Make scripts executable
        run: chmod +x install.sh scripts/*.sh tests/*.sh

      - name: Test dry run
        run: ./install.sh --dry-run

      - name: Test CLI tools installation
        run: sudo ./install.sh --cli-tools

      - name: Verify installation
        run: ./tests/verify-tools.sh
